---
- name: Install  & config PXE server
  hosts: TFTP
  vars_files:
   - secrets.yml
   - vars/hosts.yml
  become: true
  tasks:
  
     - name: Install required packages
       apt:
        name:
         - tftpd-hpa
         - nginx
         - syslinux
         - syslinux-common
         - pxelinux
         - wget
         - curl
        state: present
        update_cache: yes
   
     - name: Create directory structure
       file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
       loop:
        - "{{ tftp_root }}"
        - "{{ tftp_root }}/pxelinux.cfg"
        - "{{ tftp_root }}/ubuntu-24.04"
        - "{{ http_root }}"

     - name: Download Ubuntu 24.04.3 netboot files
       get_url:
        url: "{{ ubuntu_netboot_url }}{{ item }}"
        dest: "{{ tftp_root }}/ubuntu-24.04/{{ item | basename }}"
        mode: '0644'
        timeout: 120
       loop:
         - "ubuntu-installer/amd64/linux"
         - "ubuntu-installer/amd64/initrd.gz"
       ignore_errors: yes

     - name: Copy SYSLINUX files to TFTP root
       copy:
        remote_src: yes
        src: "/usr/lib/syslinux/modules/bios/{{ item }}"
        dest: "{{ tftp_root }}/"
        mode: '0644'
       loop:
       - ldlinux.c32
       - libutil.c32
       - menu.c32
       - libcom32.c32

     - name: Copy pxelinux.0 to TFTP root
       copy:
        remote_src: yes
        src: "/usr/lib/PXELINUX/pxelinux.0"
        dest: "{{ tftp_root }}/"
        mode: '0644'

     - name: Configure TFTP server
       copy:
        content: |
           # /etc/default/tftpd-hpa
           TFTP_USERNAME="tftp"
           TFTP_DIRECTORY="{{ tftp_root }}"
           TFTP_ADDRESS="0.0.0.0:69"
           TFTP_OPTIONS="--secure --ipv4"
        dest: /etc/default/tftpd-hpa
        mode: '0644'
       notify: restart tftpd-hpa

     - name: Create PXE menu configuration
       template:
        src: "templates/pxelinux.cfg.j2"
        dest: "{{ tftp_root }}/pxelinux.cfg/default"
        mode: '0644'

     - name: Configure Nginx for HTTP serving
       copy:
        content: |
          server {
           listen 80;
           root {{ http_root }};
           autoindex on;
           server_name _;
          
           location / {
               try_files $uri $uri/ =404;
           }
          }
        dest: /etc/nginx/sites-available/pxe
        mode: '0644'

     - name: Enable Nginx site
       file:
        src: /etc/nginx/sites-available/pxe
        dest: /etc/nginx/sites-enabled/pxe
        state: link

     - name: Disable default Nginx site
       file:
        path: /etc/nginx/sites-enabled/default
        state: absent

     - name: Ensure services are enabled and started
       service:
        name: "{{ item }}"
        state: started
        enabled: yes
       loop:
        - tftpd-hpa
        - nginx

     - name: Verify netboot files
       stat:
        path: "{{ tftp_root }}/ubuntu-24.04/{{ item }}"
       loop:
       - linux
       - initrd.gz
       register: netboot_files
  
  handlers:
        - name: restart tftpd-hpa
          service:
           name: tftpd-hpa
           state: restarted
          become: true 

        - name: restart nginx
          service:
           name: nginx
           state: restarted
          become: true

        - name: reload nginx
          service:
           name: nginx
           state: reloaded
          become: true