---
gateway : "192.168.1.1"
dns: "192.168.1.148"
tftp_root: "/srv/tftp"
http_root: "/var/www/html"
pxe_server_ip: "192.168.1.106"
ubuntu_iso_url: "https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-live-server-amd64.iso"
ubuntu_iso_filename: "ubuntu-24.04.3-live-server-amd64.iso"
autoinstall_dir: "autoinstall"
default_hostname: "ubuntu-server"
default_username: "ubuntu"
tftp_log_dir: "/var/log/tftp"
tftp_log_file: "tftp.log"
http_port: 80

vms_to_create:
 - name: "TFTP"
   ip_address: "192.168.1.106/24"
   memory: "1024"

 - name: "client"
   ip_address: "dhcp"
   memory: "4096"

