---
gateway : "192.168.1.1"
dns: "192.168.1.148"
tftp_root: "/srv/tftp"
http_root: "/var/www/html"
pxe_server_ip: "192.168.1.106"
ubuntu_netboot_url: "https://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/"
ubuntu_netboot_files:
  - "ubuntu-installer/amd64/linux"
  - "ubuntu-installer/amd64/initrd.gz"
  
vms_to_create:
 - name: "TFTP"
   ip_address: "192.168.1.106/24"
   memory: "1024"

 - name: "client"
   ip_address: "dhcp"
   memory: "1024"

